<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Unity.Addressables">
      <HintPath>..\AngryLevelLoader\libs\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>..\AngryLevelLoader\libs\Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\AngryLevelLoader\libs\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
